services:
  api-gateway:
    build:
      context: .
      dockerfile: api-gateway/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - AUTH_USER_SERVICE_URL=http://auth-user:8001
      - AUTH_ADMIN_SERVICE_URL=http://auth-admin:8002
      - BOOKS_SERVICE_URL=http://books-service:8003
      - ADMIN_SERVICE_URL=http://admin-service:8004
    depends_on:
      - auth-user
      - auth-admin
      - books-service
      - admin-service

  auth-user:
    build:
      context: .
      dockerfile: services/auth-user/Dockerfile
    ports:
      - "8001:8001"
    env_file:
      - .env
    environment:
      - PORT=8001

  auth-admin:
    build:
      context: .
      dockerfile: services/auth-admin/Dockerfile
    ports:
      - "8002:8002"
    env_file:
      - .env
    environment:
      - PORT=8002

  books-service:
    build:
      context: .
      dockerfile: services/books-service/Dockerfile
    ports:
      - "8003:8003"
    env_file:
      - .env
    environment:
      - PORT=8003

  admin-service:
    build:
      context: .
      dockerfile: services/admin-service/Dockerfile
    ports:
      - "8004:8004"
    env_file:
      - .env
    environment:
      - PORT=8004
